#+Title: Schedule
# Common Tags: family, friends, car, personal
# Class Tags: EE, SS, ENL, GYM

* School
** TODO Start laying the foundation for my project                       :SS:
	 I'll be constructing an org-mode file for this.
	 Todo:
	 - [X] Read the relevant info found here: [[~/Downloads/xilinx-iir-hardware.pdf]]
	 - [X] Create an iir-hardware.org file
	 - [X] Write down any relevant information
	 - [X] Start the general outline in VHDL (either for FIR or IIR)
	 - [X] Git repo: https://github.com/nuclearkev/iir-hardware

*** DONE FIR with internal coefficients [OVERDUE]
		DEADLINE: <2017-01-19 Thu>
		I should be able to use the actual XADC with this.
		- [X] Without pipelining (I think you need to use pipelining due to timing)
		- [X] With pipelining

*** TODO IIR with internal coefficients
		DEADLINE: <2017-01-26 Thu>
		Once again, with XADC.
		- [ ] Without pipelining
		- [ ] With pipelining

*** TODO Figure out coefficients Zynq->IP
		DEADLINE: <2017-02-02 Thu>
		I'm thinking serial, however, I am not sure how to receive them in the
		IP. Do I need to create a serial controller inside the IP? Instantiate a
		serial controller model inside? Or can I get away with rerouting the input
		value at the falling edge of the clock pulse? See below:

		#+NAME: Serial Receiever
		#+BEGIN_SRC vhdl
		process
		  if(falling_edge(Clk)) then

			-- Shift the data array and feed in the new data
			variable i : integer := 0;
      for i in 0 to 4 loop
        data(i+1) <= data(i);
      end loop;
      data(0) <= data_in;

		end process;
		#+END_SRC

*** TODO Have coefficients shipping
		DEADLINE: <2017-02-23 Thu>
		Maybe have an FSM or something. IDFK

** TODO Apply to places																						 :personal:
	 - [X] Northrop (Rob)
	 - [ ] L3 (any branch)

* Work
* Extra
** TODO Learn C++
	 Ask Jonny some stuff

** TODO Read Daniel
	 DEADLINE: <2017-01-24 Tue>
