#+Title: Schedule
# Common Tags: family, friends, car, personal
# Class Tags: EE, SS, ENL, GYM

* School
** DONE Chapter 1 problems                                               :EE:
	 DEADLINE: <2017-01-13 Fri>
	 Numbers: 1-2, 1-3, 1-6, 1-7, 1-11

	 *The problems in my PDF 16th edition book are different from the book used*
	 *in class. Get the problems from M@*

** TODO Start laying the foundation for my project                       :SS:
	 I'll be constructing an org-mode file for this.
	 Todo:
	 - [X] Read the relevant info found here: [[~/Downloads/xilinx-iir-hardware.pdf]]
	 - [X] Create an iir-hardware.org file
	 - [X] Write down any relevant information
	 - [ ] Start the general outline in VHDL (either for FIR or IIR)
	 - [X] Git repo: https://github.com/nuclearkev/iir-hardware

*** TODO FIR with internal coefficients
		DEADLINE: <2017-01-19 Thu>
		I should be able to use the actual XADC with this.
		- [ ] Without pipelining
		- [ ] With pipelining

*** TODO IIR with internal coefficients
		DEADLINE: <2017-01-26 Thu>
		Once again, with XADC.
		- [ ] Without pipelining
		- [ ] With pipelining

*** TODO Figure out coefficients Zynq->IP
		DEADLINE: <2017-02-02 Thu>
		I'm thinking serial, however, I am not sure how to receive them in the
		IP. Do I need to create a serial controller inside the IP? Instantiate a
		serial controller model inside? Or can I get away with rerouting the input
		value at the falling edge of the clock pulse? See below:

		#+NAME: Serial Receiever
		#+BEGIN_SRC vhdl
		process
		  if(falling_edge(Clk)) then

			-- Shift the data array and feed in the new data
			variable i : integer := 0;
      for i in 0 to 4 loop
        data(i+1) <= data(i);
      end loop;
      data(0) <= data_in;

		end process;
		#+END_SRC

*** TODO Have coefficients shipping
		DEADLINE: <2017-02-23 Thu>
		Maybe have an FSM or something. IDFK

** TODO Apply to places																						 :personal:
	 - [X] Northrop (Rob)
	 - [ ] L3 (any branch)


* Work
* Extra
** DONE Learn something about C++
	 DEADLINE: <2016-12-09 Fri>
	 I'd like to know some C++ so that it looks good on my resume. This
	 is because a lot of places like C++ experience.

	 Jonny's AVR/Arduino library should be a really good tool to learn
	 it.
