#+TITLE: Summer Goals
# This document contains some of the things I'd like to complete 2016 summer

* Self-Related
** Hit the gym
	 I would like to try and go to the gym at least 3 days a week. However, I
	 would prefer to go closer to 4 or 5 times a week.
** The stuff
	 The reboot date is <2016-06-08 Wed>
** Be nicer
	 I'm pretty rude sometimes. Try and be a little nicer you jackass.


* Programming Related
** Better my Common Lisp skills
	 I would like to become better at Common Lisp by using more lambdas and higher
	 order functions. Also, I would like to do more advanced Lisp programming by
	 making more complicated programs
*** Fix the division functions in the big-number library
		Division is an ugly mess. It needs to be redone and in a more clever way.
		It also needs to be more readable and needs to support fractions.
*** Maybe finish the polynomial program
		I don't know if I care about this program anymore...
*** Write a cool program that does something cool
		Maybe another math program but something more impressive.
** Better my Rust skills
	 Maybe actually write a program in Rust??
** Learn more Emacs Lisp
	 Make some more functions because Emacs is life.
** If I get the job at RallyAll, learn Java/Typescript
	 That's what I need to work there...
*** Learn Angular
		They use this too


* Job Related
** Maybe be a job at RallyAll
	 I still don't know if I want to work there.
** Theater
*** Spend more time with the projectors
		The projects are fine but they could be better. I wish to make them better
		though.
*** Train some idiots for projection
		I don't know about Phoebe or Zane; they don't seem like they're gonna work
		as well as I thought... Cole?
