#+TITLE: Cornelius

* Basics
	Lvl: 1
	Class: Orb Master
	Background:
	Race: Half-Gnome
	Languages: Common, Elvish, Gnomish
	Alignment: Neutral
  Age: 22

	XP: 0 (300)

	HP: 9
	Temp HP:
	AC: 12
	Speed: 30
	Initiative:
	Proficiency Bonus: 2
	Hit Die: 1d6 per level (# 1 : used 0)

	Inspiration:
	Death:

* Ability Scores
	STR: 9 (-1)
	DEX: 11 (+0)
	CON: 12 (+1)
	INT: 12 (+1)
	WIS: 19 (+4)
	CHA: 18 (+4)

* Saving Throws
		STR: -1
		DEX: 0
		CON: +1
		INT: +1
		WIS: +6 *
		CHA: +6 *

* Skills
	Acrobatics (Dex)
	Animal handling (Wis)
	Arcana (Int)
	Athletics (Str)
	Deception (Cha) *
	History (Int)
	Insight (Wis) *
	Intimidation (Cha)
	Investigation (Int)
	Medicine (Wis)
	Nature (Int)
	Perception (Wis) *
	Performance (Cha)
	Persuasion (Cha) *
	Religion (Int)
	Sleight of hand (Dex)
	Stealth (Dex)
	Survival (Wis)

* Attacks

* Items

  Money:
  - GP: 5

* Backstory
  He just showed up just like the others. For some reason he can control these
  orbs and he can't figure out how or why.

* Appearance
  Cornelius isn't very impressive in stature. He stands about 4'5" and isn't
  very muscular. He sports typical safari gear: tan shorts, an olive green
  shirt, a dark tan colored backpack, and a white-ish tan bug catcher
  hat. Around his belt are 13 spheres called orbs. They glow an attractive
  asortment of colors, however, there seems to be pairs of colors. His face
  looks young and you would mistake him for a child or teenager if it wasn't for
  his sideburns. Under his hat is mostly a full head of hair, except in the
  back. The top of his head (completely hidden by the hat and located where you
  "hair swirl" is) is a metal door-like thing that can be opened like an
  iris. On the inside of this is where his brain would be but instead there is a
  hollow metal area with an orb inside. All the colors of the other orbs are
  displayed from this orb. This is the Master Orb. What exactly is this guy?
